from google import genai
import streamlit as st


# -------------------------
# Gemini client
# -------------------------

client = genai.Client(
    api_key=st.secrets["GEMINI_API_KEY"]
)


def generate_lyrics(prompt, genre, emotion):
    """
    Generate lyrics for a song based on a prompt,
    genre, and emotion.
    """

    prompt = f"""
    Generate original lyrics for a song with the following prompt:

    {prompt}

    The lyrics should be in {genre} style and should
    be suitable for a {emotion} emotion.

    Make the lyrics creative and original.
    """

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt
    )

    return response.text


# -------------------------
# Page setup
# -------------------------

st.set_page_config(
    page_title="Lyrics AI",
    page_icon="🎵",
    layout="wide"
)


# -------------------------
# Header
# -------------------------

st.title("🎵 Lyrics AI")

st.write(
    "Welcome to Lyrics AI! Generate unique lyrics based on "
    "the prompt you provide."
)

st.write(
    "Enter your prompt, choose a genre and emotion, "
    "and let AI create a unique song for you!"
)


# -------------------------
# Lyrics settings
# -------------------------

st.subheader("What's on your mind?")

prompt = st.text_area(
    "Prompt",
    placeholder="Example: A song about the ocean...",
    height=120
)

col1, col2 = st.columns(2)

with col1:
    genre = st.selectbox(
        "🎸 Genre",
        [
            "Pop",
            "Rock",
            "Hip-Hop",
            "Jazz",
            "Classical",
            "Country",
            "R&B",
            "Electronic",
            "Indie",
            "Alternative",
            "Indian",
            "Chinese",
            "Metal",
            "Punk",
            "Reggae",
            "Salsa",
        ]
    )

with col2:
    emotion = st.selectbox(
        "😊 Emotion",
        [
            "No preference",
            "Happy",
            "Sad",
            "Angry",
            "Nostalgic",
            "Romantic",
            "Energetic",
            "Melancholic",
            "Reflective",
            "Hopeful",
            "Longing"
        ]
    )


# -------------------------
# Generate button
# -------------------------

st.divider()

if st.button(
    "🎵 Generate Lyrics",
    type="primary",
    use_container_width=True
):

    if not prompt.strip():
        st.warning("Please enter a prompt.")

    else:
        st.subheader("✨ Your Lyrics")

        st.info(
            f"Generating a {genre.lower()} song "
            f"with a {emotion.lower()} vibe..."
        )

        lyrics = generate_lyrics(
            prompt,
            genre,
            emotion
        )

        st.markdown(lyrics)


# -------------------------
# Disclaimer
# -------------------------

st.divider()

st.caption(
    "⚠️ Lyrics generated by AI are for informational purposes only. "
    "Check the lyrics and their appropriateness yourself before using."
)
